name: speedrun
version: '${project.version}'
main: me.herbyvor.speedrun.Speedrun
api-version: 1.20
authors: [ herbyvor ]
description: event plugin for my 100 followers
website: https://play.noskillworld.fr
depend: [DeadlyDisasters]
commands:
  sr_start:
    description: lance le jeu
    usage: /<command>
  sr_stop:
    description: met fin au jeu
    usage: /<command>
  sr_pause:
    description: met le jeu en pause
    usage: /<command>
  sr_setEndSpot:
    description: set la position de l'autel de fin
    usage: /<command>
  sr_test:
    description: test command for dev
    usage: /<command>
